name: build-sphinx
on:
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "sphinx-docs/"
        pre-build-command: "pip install sphinx-rtd-theme"
    - name: Commit Documentation Changes
      run: |
        git clone https://github.com/ngpaladi/py2700.git --branch docs --single-branch docs
        cp -r sphinx-docs/_build/html/* docs/
        cd docs
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update Sphinx Documentation" -a || true
    - name: Push Documentation Changes
      uses: ad-m/github-push-action@master
      with:
        branch: docs
        directory: docs
        github_token: ${{ secrets.GITHUB_TOKEN }}